apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hello-service
spec:
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort # Use NodePort if you want external access
