apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service-deployment
  labels:
    app: world-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
        - name: world-service
          image: world-service:1.0 # Make sure this matches your Docker image tag
          ports:
            - containerPort: 8081
