apiVersion: v1
kind: Service
metadata:
  name: spring-boot-world-service
spec:
  selector:
    app: world-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001  # Optional: Expose this service on this node port
  type: NodePort
